alias ins="sudo apt-get install"
alias upd='sudo apt-get update'
alias upg='sudo apt-get upgrade'
alias renm='sudo service network-manager restart'
alias rea='sudo service apache2 restart'
alias resql='sudo service mysql restart'
alias ..='cd ..'
alias ...='cd ../..'
alias cdd='cd ~/Desktop'
alias pyserve='python -m SimpleHTTPServer'
alias pytohn='python'
alias ipytohn='ipython'
alias df='df -h'
alias hist='cat ~/.eternal_history | grep'
alias iqt='ipython qtconsole --colors=linux'
