alias ins='sudo apt-get install'
alias upd='sudo apt-get update'
alias renm='sudo service network-manager restart'
alias rea='sudo service apache2 restart'
alias ..='cd ..'
alias s='sudo'
alias v='vim'
alias namp='nmap'
