#!/usr/bin/env bash
cd "$(dirname "$0")"
REPO_PATH=$(pwd)

for src in 'bashrc' 'inputrc' 'vimrc' 'bash_aliases' 'vim_cscope'
do
    if [ -e "$HOME/.$src" ]
    then
        mv -i $HOME/.$src $HOME/.$src.bak
        echo "Moved $HOME/.$src to $HOME/.$src.bak"
    fi
    ln -s $REPO_PATH/$src $HOME/.$src
    echo "Symlinked $HOME/.$src"
done

NVIM_DIR=$HOME/.config/nvim
mkdir -p $NVIM_DIR
if [ -e "$NVIM_DIR/init.vim" ]
then
    mv -i $NVIM_DIR/init.vim $NVIM_DIR/init.vim.bak
    echo "Moved $NVIM_DIR/init.vim to $NVIM_DIR/init.vim.bak"
fi
ln -s $REPO_PATH/init.vim $NVIM_DIR/init.vim
echo "Symlinked $NVIM_DIR/init.vim"

